export const mockAnalysis = {
  startup: {
    name: "NovaClaim AI",
    industry: "InsurTech / AI Operations",
    stage: "Seed",
    geography: "EU (Berlin)",
  },
  scores: {
    fit: 7.8,
    novelty: 7.8,
    foresight: 8.2,
    crmMatches: 4,
  },
  memory: {
    profile: {
      startupName: "NovaClaim AI",
      founderName: "Lena Hartmann",
      industry: "InsurTech",
      technology: "LLM-based agentic workflows",
      problem: "Manual claims processing is slow and costly",
      solution: "AI-native claims automation platform",
      businessModel: "B2B SaaS, per-seat + usage",
      fundingStage: "Seed ($3M)",
      targetCustomer: "Mid-market European insurers",
      geography: "EU, focus DACH",
    },
    similar: [
      { name: "ClaimGenius", similarity: 86, reason: "Same vertical, US-focused", decision: "Passed", note: "Strong team but weak EU traction" },
      { name: "Shift Technology", similarity: 74, reason: "Adjacent fraud detection", decision: "Tracking", note: "Incumbent, not direct competitor" },
      { name: "Omni:us", similarity: 71, reason: "EU InsurTech, document AI", decision: "Met 2x", note: "Pivoted, lost momentum" },
      { name: "Tractable", similarity: 68, reason: "Computer vision claims", decision: "Passed", note: "Different modality" },
      { name: "FlowClaim", similarity: 64, reason: "Workflow automation", decision: "Tracking", note: "Earlier stage, watch closely" },
    ],
    openSource: [
      { name: "Lemonade (public)", similarity: 72, reason: "Public InsurTech filings (S-1, 10-K)", decision: "Reference", note: "Benchmark for AI-claims unit economics" },
      { name: "Root Insurance", similarity: 65, reason: "Crunchbase + SEC disclosures", decision: "Reference", note: "Cautionary tale on CAC scaling" },
      { name: "Hippo Insurance", similarity: 61, reason: "Public filings, news coverage", decision: "Reference", note: "Pivot to platform model documented" },
      { name: "Clearcover", similarity: 58, reason: "Press releases, ProductHunt", decision: "Reference", note: "API-first claims approach" },
      { name: "Wefox (open data)", similarity: 54, reason: "EU public funding records", decision: "Reference", note: "DACH distribution playbook" },
    ],
    relationship: ["Lena Hartmann", "Marc Weber (Angel)", "Sofia Klein (Partner)", "InsureTech Co. (Portfolio)"],
    crm: {
      found: true,
      lastInteraction: "2025-09-14",
      owner: "Sofia Klein",
      stage: "First call complete",
      nextAction: "Request pitch deck + customer references",
    },
    questions: [
      "What is your current ARR?",
      "Who is the economic buyer?",
      "What makes the product defensible?",
      "Which competitors do customers compare you with?",
      "What proof do you have that this problem is urgent?",
    ],
  },
  novelty: {
    breakdown: [
      { label: "Differentiation", value: "High", level: "high" },
      { label: "Competition", value: "Medium", level: "medium" },
      { label: "Market gap", value: "Strong", level: "high" },
      { label: "Customer urgency", value: "Medium", level: "medium" },
      { label: "Commercial feasibility", value: "Good", level: "high" },
    ],
    competitors: [
      { name: "ClaimGenius", category: "Direct", similarity: 86, strength: "Strong US presence", weakness: "No EU compliance", difference: "EU-first, GDPR-native", website: "claimgenius.example" },
      { name: "Shift Technology", category: "Incumbent", similarity: 74, strength: "Enterprise relationships", weakness: "Slow innovation", difference: "Agentic AI, faster deploy", website: "shift.example" },
      { name: "Omni:us", category: "Direct", similarity: 71, strength: "Document AI", weakness: "Lost momentum", difference: "End-to-end workflow", website: "omnius.example" },
      { name: "Tractable", category: "Adjacent", similarity: 68, strength: "Computer vision", weakness: "Narrow use case", difference: "Broader claim types", website: "tractable.example" },
      { name: "FlowClaim", category: "Early-stage", similarity: 64, strength: "Modern stack", weakness: "Tiny team", difference: "Mature product", website: "flowclaim.example" },
      { name: "Friss", category: "Incumbent", similarity: 58, strength: "Fraud expertise", weakness: "Legacy UI", difference: "AI-native UX", website: "friss.example" },
      { name: "EIS Group", category: "Incumbent", similarity: 55, strength: "Full platform", weakness: "Expensive, slow", difference: "Lightweight, fast", website: "eis.example" },
      { name: "Snapsheet", category: "Adjacent", similarity: 52, strength: "Mobile claims", weakness: "Auto-only", difference: "Multi-line", website: "snapsheet.example" },
      { name: "Sprout.ai", category: "Direct", similarity: 50, strength: "UK presence", weakness: "Small footprint", difference: "DACH-first", website: "sprout.example" },
      { name: "Akur8", category: "Adjacent", similarity: 47, strength: "Pricing AI", weakness: "Different problem", difference: "Claims, not pricing", website: "akur8.example" },
      { name: "Cytora", category: "Adjacent", similarity: 45, strength: "Risk intake", weakness: "Underwriting only", difference: "Post-bind workflow", website: "cytora.example" },
      { name: "Lemonade", category: "Indirect", similarity: 42, strength: "Consumer brand", weakness: "Vertical insurer", difference: "B2B platform", website: "lemonade.example" },
      { name: "Wefox", category: "Indirect", similarity: 38, strength: "Distribution", weakness: "Not infra", difference: "Infra play", website: "wefox.example" },
      { name: "OpenClaims", category: "Open-source", similarity: 35, strength: "Free", weakness: "No support", difference: "Commercial-grade", website: "openclaims.example" },
      { name: "Zelros", category: "Adjacent", similarity: 32, strength: "Recommendations", weakness: "Different layer", difference: "Operations focus", website: "zelros.example" },
    ],
    competitorMap: {
      "Direct competitors": ["ClaimGenius", "Omni:us", "Sprout.ai"],
      "Indirect competitors": ["Lemonade", "Wefox"],
      "Enterprise incumbents": ["Shift Technology", "Friss", "EIS Group"],
      "Early-stage startups": ["FlowClaim"],
      "Open-source / alternatives": ["OpenClaims"],
    },
    gaps: [
      "Underserved mid-market EU insurer segment",
      "Missing workflow integration with legacy core systems",
      "Weak localization for DACH market",
      "Lack of compliance-first (GDPR/Solvency II) solution",
      "Expensive enterprise-only solutions dominate",
    ],
    segments: {
      primaryCustomer: "Mid-market European insurers ($100M–$2B GWP)",
      secondaryCustomer: "Insurance MGAs and TPAs",
      buyerPersona: "Head of Claims / COO",
      userPersona: "Claims handlers and team leads",
      industryVertical: "P&C Insurance",
      budgetOwner: "Chief Operations Officer",
    },
    financial: {
      revenueModel: "B2B SaaS, per-seat + usage-based",
      pricingBenchmark: "$50k–$300k ACV",
      willingnessToPay: "High (clear ROI on claim cycle time)",
      salesCycle: "6–9 months (medium difficulty)",
      cacRisk: "Medium",
      grossMargin: "75–82% (strong)",
    },
    saturation: "Medium",
    insight: "NovaClaim is meaningfully differentiated through its EU-first compliance posture and agentic workflow approach. The market is competitive but no incumbent owns the mid-market DACH segment, giving room for category leadership.",
  },
  foresight: {
    breakdown: [
      { label: "Market timing", value: "Strong", level: "high" },
      { label: "Technology momentum", value: "High", level: "high" },
      { label: "Regulatory tailwind", value: "Medium", level: "medium" },
      { label: "Funding activity", value: "Growing", level: "high" },
      { label: "Adoption potential", value: "High", level: "high" },
      { label: "Strategic exit potential", value: "Medium", level: "medium" },
    ],
    trends: [
      { name: "AI automation", momentum: "Accelerating", why: "LLMs make domain workflows automatable", relevance: "Core to product" },
      { name: "Vertical SaaS", momentum: "Strong", why: "Investors reward focused verticals", relevance: "Direct fit" },
      { name: "Agentic workflows", momentum: "Emerging", why: "Multi-step reasoning unlocks ops automation", relevance: "Architecture aligned" },
      { name: "Compliance automation", momentum: "Growing", why: "EU AI Act + Solvency II pressure", relevance: "Differentiator" },
      { name: "Data-driven operations", momentum: "Mature", why: "Insurers digitizing core ops", relevance: "Tailwind" },
    ],
    timing: "Good timing",
    category: {
      current: "Claims automation software",
      future: "AI-native Insurance Operations Platform",
      maturity: "Early — emerging in next 24 months",
      potential: "High — defensible category creation possible",
    },
    scenarios: {
      best: "Becomes default ops layer for EU mid-market insurers; $50M ARR within 4 years; strategic acquisition by tier-1 incumbent.",
      base: "Steady growth to $10–20M ARR, healthy unit economics, Series B raised, regional leader.",
      worst: "Long sales cycles compress runway; incumbents copy features; struggles past Series A.",
    },
    opportunity: {
      acquisitionTarget: "High — Guidewire, Duck Creek, Shift",
      adjacentExpansion: "Underwriting, fraud detection, customer comms",
      defensibility: "Proprietary EU claims data + workflow graph",
      systemOfRecord: "Strong potential as ops backbone",
    },
    risks: [
      "Incumbents copying features",
      "Long enterprise sales cycles",
      "Data privacy / compliance barriers",
      "Weak customer urgency in some segments",
      "Integration complexity with legacy core systems",
    ],
    thesis: "This startup is attractive if it can prove strong customer urgency, deep workflow integration, and defensible data advantages. The market is moving in the right direction, but the company must show why it can win against both startups and incumbents.",
  },
  inputs: {
    sources: [
      { name: "Granola Notes", status: "Simulated" },
      { name: "Affinity CRM", status: "Simulated" },
      { name: "Web Research", status: "Simulated" },
      { name: "Internal VC Memory", status: "Simulated" },
    ],
    confidence: {
      dataQuality: "Medium",
      missing: ["ARR", "Customer references", "Pricing", "Competitor proof"],
      nextStep: "Request pitch deck and customer metrics",
    },
  },
  foresightPayload: null as null | {
    parsed?: Record<string, unknown>;
    literature?: Record<string, unknown>;
    bundle?: Record<string, unknown>;
  },
};

export type AnalysisData = typeof mockAnalysis;
